//! A sparse-set-backed map implementation. The map [`Key`]s are created and managed by a [`KeyRegistry`]. The [`SecondaryMap`] is a map from [`Key`]s to arbitrary values.
//!
//! Both the `KeyRegistry` and the `SecondaryMap` are designed to provide efficient operations for (in order of importance):
//! 1. **Iteration**: Iterating over all entries of both the `KeyRegistry` and the `SecondaryMap` is O(n), where n is the number of entries in the container. This is achieved by storing the entries in a dense vector. Both containers provide a read-only slice of their entries. However, no guarantee is made on the order of the entries in the slice, as it may change after insertions and deletions.
//! 2. **Random access**: Checking for the presence of a key in the `KeyRegistry` or accessing the value associated with a key in the `SecondaryMap` is O(1). This is achieved by storing a sparse vector of indices pointing to the dense vector. The tradeoff is the memory usage of the sparse vector (up to O(m), where m is the number of keys in the registry) and an extra level of indirection when accessing entries. Random access is therefore slower than a vector but still O(1).
//! 3. **Insertion and deletion**: Insertion and deletion of entries in both the `KeyRegistry` and the `SecondaryMap` are O(1) in the average case, but insertion can be O(n), O(m) or O(m+n) if the sparse vector, the dense vector or both need to be resized. Deletion is always O(1). Deleting keys from the `KeyRegistry` allows their indices to be reused for new keys, keeping `m` low and ensuring fast operations of both the `KeyRegistry` and the `SecondaryMap` over time. Deleted keys are not automatically deleted from the `SecondaryMap`s. However, deleted keys can be removed by calling [`SecondaryMap::remove_deleted`][crate::SecondaryMap::remove_deleted] with the registry.
//!
//! Those types are designed to be used in an Entity-Component-System (ECS) architecture, where the `KeyRegistry` is used to manage entity IDs and the `SecondaryMap` is used to store components associated with those entities. However, they can be used in any context where iteration and random access are both important and keys generated by a registry are sufficient.

pub use key::{Key, KeyRegistry};
pub use map::SecondaryMap;

mod key;
mod map;

#[doc = include_str!("../README.md")]
#[cfg(doctest)]
pub struct ReadmeDoctests;
