//! A sparse-set-backed map implementations. The map [`Key`]s are created and managed by either a [`KeyRegistry`] or a [`PrimaryMap`]. The [`SecondaryMap`] is a map from [`Key`]s to arbitrary values.
//!
//! The `KeyRegistry`, `PrimaryMap` and the `SecondaryMap` containers are designed to provide efficient operations for (in order of importance):
//! 1. **Iteration**: Iterating over all entries of both the `KeyRegistry` and the `SecondaryMap` is O(n), where n is the number of entries in the container. This is achieved by storing the entries in a dense vector. Both containers provide a read-only slice of their entries. However, no guarantee is made on the order of the entries in the slice, as it may change after insertions and deletions.
//! 2. **Random access**: Checking for the presence of a key in the `KeyRegistry` or accessing the value associated with a key in `PrimaryMap` or a `SecondaryMap` is O(1). This is achieved by storing a sparse vector of indices pointing to the dense vector. The tradeoff is the memory usage of the sparse vector (up to O(m), where m is the number of keys in the registry/primary map) and an extra level of indirection when accessing entries. Random access is therefore slower than a vector but still O(1).
//! 3. **Insertion and deletion**: Insertion and deletion of entries in all three containers are O(1) in the average case, but insertion can be O(n), O(m) or O(m+n) if the sparse vector, the dense vector or both need to be resized. Deletion is always O(1). Deleting keys from the `KeyRegistry` or `PrimaryMap` allows their indices to be reused for new keys, keeping `m` low and ensuring fast operations of all containers over time. Deleted keys are not automatically deleted from the `SecondaryMap`s. However, deleted keys can be removed by calling [`SecondaryMap::remove_deleted_from_primary_map`] with the associated `PrimaryMap` or [`SecondaryMap::remove_deleted_from_registry`] with the associated `KeyRegistry`.
//!
//! Those types are designed to be used in an Entity-Component-System (ECS) architecture, where the `KeyRegistry` is used to manage entity IDs and the `SecondaryMap` is used to store components associated with those entities. However, they can be used in any context where iteration and random access are both important and keys generated by a registry are sufficient.

#![warn(missing_docs)]

pub use key::{Key, KeyRegistry};
#[doc(inline)]
pub use primary_map::PrimaryMap;
#[doc(inline)]
pub use secondary_map::SecondaryMap;

mod key;
pub mod primary_map;
pub mod secondary_map;

/// An entry in the dense vector of a [`PrimaryMap`] or a [`SecondaryMap`]. Contains the value of the entry and its associated key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DenseEntry<T> {
    /// The value of the entry.
    pub value: T,

    /// The key associated with the entry.
    pub key: Key,
}

#[doc = include_str!("../README.md")]
#[cfg(doctest)]
pub struct ReadmeDoctests;
