[package]
name = "lightning"
version = "0.1.0"
authors = ["Lorin Jacot <71598369+lorinjacot@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = [] }
dioxus-native = { version = "0.7.2", optional = true }
uuid = { workspace = true, features = ["js", "v4"] }
web-sys = { workspace = true, features = ["Document", "Element", "HtmlCanvasElement", "Window"], optional = true }
wgpu.workspace = true

[features]
default = ["desktop"]
web = ["dioxus/web", "dep:web-sys"]
desktop = ["dioxus/native", "dep:dioxus-native"]

[build-dependencies]
cfg_aliases.workspace = true
