[package]
name = "billiard"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger.workspace = true
glam.workspace = true
image.workspace = true
log.workspace = true
notify.workspace = true
numpy.workspace = true
pollster.workspace = true
pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-ffi.workspace = true
tonner = { workspace = true, features = ["python"] }
wgpu.workspace = true
winit.workspace = true
