[package]
name = "billiard"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger.workspace = true
image.workspace = true
pollster.workspace = true
pyo3 = { workspace = true, features = ["auto-initialize"] }
pyo3-ffi.workspace = true
storm.workspace = true
wgpu.workspace = true
winit.workspace = true
