[package]
name = "storm"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
approx = "0.5.1"
bitflags = "2.9.1"
bytemuck.workspace = true
dashmap.workspace = true
data-url = "0.3.1"
glam = { workspace = true, features = ["bytemuck"] }
image = { version = "0.25.6", default-features = false, features = ["hdr"] }
log.workspace = true
mikktspace = { version = "0.3.0", features = ["glam"], default-features = false }
pollster.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.140"
serde_repr = "0.1.20"
thiserror.workspace = true
uuid = { workspace = true, features = ["js", "serde", "v4"] }
wgpu = { workspace = true }

[dev-dependencies]
winit = "0.30.12"
