[package]
name = "storm"
version = "0.1.0"
edition = "2024"

[dependencies]
approx.workspace = true
bitflags.workspace = true
bytemuck.workspace = true
dashmap.workspace = true
glam = { workspace = true, features = ["bytemuck"] }
image.workspace = true
log.workspace = true
mikktspace = { version = "0.3.0", features = ["glam"], default-features = false }
numpy = { workspace = true, optional = true }
pollster.workspace = true
pyo3 = { workspace = true, optional = true }
thiserror.workspace = true
uuid = { workspace = true, features = ["js", "serde", "v4"] }
wgpu = { workspace = true }

[dev-dependencies]
winit.workspace = true

[features]
pyo3 = ["dep:pyo3", "dep:numpy"]
