[package]
name = "tonner"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Placeholder for an upcoming physics simulation engine"
homepage = "https://tonner.jacot.cloud"
repository = "https://github.com/lorinjacot/tonner"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "jupyter-server"
required-features = ["python", "window"]

[dependencies]
bitflags.workspace = true
bytemuck.workspace = true
dashmap.workspace = true
glam = { workspace = true, features = ["bytemuck"] }
image.workspace = true
log.workspace = true
mikktspace = { version = "0.3.0", features = ["glam"], default-features = false }
numpy = { workspace = true, optional = true }
pollster = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true, features = ["uuid"] }
thiserror.workspace = true
uuid = { workspace = true, features = ["v4"] }
wasm-bindgen = { workspace = true, optional = true }
wgpu.workspace = true
winit = { workspace = true, optional = true }

[features]
python = ["dep:pyo3", "dep:numpy", "dep:pollster"]
java-script = ["dep:wasm-bindgen"]
window = ["dep:winit"]

[dev-dependencies]
pollster.workspace = true
winit.workspace = true
