[package]
name = "tonner"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Placeholder for an upcoming physics simulation engine"
homepage = "https://tonner.jacot.cloud"
repository = "https://github.com/lorinjacot/tonner"
readme = "README.md"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
glam.workspace = true
log.workspace = true
numpy = { workspace = true, optional = true }
pyo3 = { workspace = true, optional = true }
sparse-keyed.workspace = true

[dev-dependencies]
env_logger.workspace = true

[features]
pyo3 = ["dep:pyo3", "dep:numpy"]
