[project]
name = "tonner"
dynamic = [
    "version",
    "description",
    "readme",
    "urls",
    "authors",
    "license",
    "keywords",
]
dependencies = [
    "numpy >= 2.4.4",
    "ipykernel >= 7.2.0",
    "jupyter_client >= 4.1.0",
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["python"]
no-default-features = true
python-source = "python"
module-name = "tonner._tonner"