class Context: ...

class TonnerWorld:
    def __init__(self, ctx: Context) -> None: ...
    def new_entity(self) -> TonnerEntity: ...

class TonnerEntity:
    def __init__(self, world: TonnerWorld) -> None: ...
